### ISSUE TITLE
Missing instructions

### ISSUE THREAD

**Issue by DevFil** [91DarioDev/iplogger#1]

**Comment by 91DarioDev** [comment]
Actually you only have to get files, rename config.example.php in config.php and replace data.
the url for the grabber will be
domain.com/index.php
or if you want to get also a reference of who clicked you add it in query string like
domain.com/index.php?id=YOUR_REFERENCE

sorry but I’m not interested in writing instructions, because it’s no more mantened

**Comment by DevFil** [comment]
Thanks for the reply.
